name: Hello World Workflow

on:
  workflow_dispatch: # Allows manual triggering of the action remotely

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Print Hello World
        run: |
          echo "${{ github.event.client_payload.branch }} ${{ github.ref_name }}"
          if [[ "${{ github.event.client_payload.branch }}" != ${{ github.ref_name }} ]]; then
            echo "Skipping. This event is for branch ${{ github.event.client_payload.branch }}."
            exit 0
          fi
          echo "Running workflow for main"
