name: Hello World Workflow

on:
  repository_dispatch:
    types: [hello-world-event]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: |
          echo "${{ github.event.client_payload.branch }}"
          if [[ "${{ github.event.client_payload.branch }}" != "master" ]]; then
            echo "Skipping. This event is for branch ${{ github.event.client_payload.branch }}."
            exit 0
          fi
          echo "Running workflow for master"
