name: Hello World Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World! test"
